import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { XAIPrediction } from "@/data/xai-molecules";

export const ExportButton = ({ prediction }: { prediction: XAIPrediction }) => {
  const handleExport = () => {
    const lines = [
      `VITALIS AI — XAI Analysis Report`,
      `${"=".repeat(50)}`,
      `Generated: ${new Date().toISOString()}`,
      ``,
      `MOLECULE: ${prediction.molecule}`,
      `SMILES: ${prediction.smiles}`,
      `Formula: ${prediction.descriptors.molecularFormula}`,
      ``,
      `--- PREDICTION SUMMARY ---`,
      `Overall Score: ${prediction.overallScore}%`,
      `Confidence: ${prediction.confidence}%`,
      `Verdict: ${prediction.verdict}`,
      ``,
      `--- AI EXPLANATION ---`,
      prediction.naturalLanguageExplanation,
      ``,
      `--- MOLECULAR DESCRIPTORS ---`,
      `Molecular Weight: ${prediction.descriptors.molecularWeight} Da`,
      `LogP: ${prediction.descriptors.logP}`,
      `H-Bond Donors: ${prediction.descriptors.hBondDonors}`,
      `H-Bond Acceptors: ${prediction.descriptors.hBondAcceptors}`,
      `Rotatable Bonds: ${prediction.descriptors.rotatableBonds}`,
      `TPSA: ${prediction.descriptors.tpsa} Å²`,
      `Aromatic Rings: ${prediction.descriptors.aromaticRings}`,
      `Drug-likeness: ${Math.round(prediction.descriptors.drugLikeness * 100)}%`,
      `Bioavailability: ${Math.round(prediction.descriptors.bioavailability * 100)}%`,
      ``,
      `--- SHAP FEATURE IMPORTANCE ---`,
      ...prediction.shapFeatures.map(f =>
        `  ${f.feature}: ${f.shapValue >= 0 ? '+' : ''}${(f.shapValue * 100).toFixed(1)}% (${f.actualValue}) — ${f.explanation}`
      ),
      ``,
      `--- LIME WEIGHTS ---`,
      ...prediction.limeWeights.map(w =>
        `  ${w.feature}: ${w.weight >= 0 ? '+' : ''}${(w.weight * 100).toFixed(0)}%`
      ),
      ``,
      `--- DECISION PATHWAY ---`,
      ...prediction.decisionPath.map((s, i) =>
        `  ${i + 1}. ${s.node}: ${s.result} (${s.condition})`
      ),
      ``,
      `--- CONFIDENCE BREAKDOWN ---`,
      ...prediction.confidenceBreakdown.map(b =>
        `  ${b.aspect}: ${b.value}%`
      ),
      ``,
      `--- DISCLAIMER ---`,
      `This analysis is generated by AI models and should be validated experimentally.`,
      `Predictions are based on molecular descriptors and rule-based filters.`,
    ];

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `xai-report-${prediction.molecule.toLowerCase().replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Button variant="outline" size="sm" className="h-7 text-[10px] gap-1.5" onClick={handleExport}>
      <Download className="w-3 h-3" />
      Export Report
    </Button>
  );
};
